# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'WeeDoo' do
    pod 'Alamofire', '~> 3.4'
    pod 'Google/SignIn'
    pod 'IQKeyboardManager'
    pod 'MBProgressHUD'
    pod 'Fabric'
    pod 'TwitterKit'
end