# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'WeeDoo' do
    pod 'Alamofire', '~> 3.4'
    pod 'Google/SignIn'
    pod 'MBProgressHUD'
    pod 'Fabric'
    pod 'TwitterKit'
    pod 'CVCalendar', '~> 1.2.9'
    pod 'IQKeyboardManagerSwift', '4.0.3'
    pod 'Gloss',      '~> 0.7.3'
    pod 'Kingfisher', '~> 2.4.1'
    pod 'Firebase'
    pod 'Firebase/Messaging'
    pod 'SnapKit', '~> 0.15.0'
end